###  **Seção 1: Otimização de Portfólio com Matriz de Covariância e Restrição de Cardinalidade**

A otimização de portfólio é uma ferramenta usada para decidir **como alocar capital entre diferentes ativos financeiros**, de forma a **maximizar o retorno esperado** e **minimizar o risco total do portfólio**.

---

####  **Objetivo do Problema**

Queremos encontrar a melhor combinação de ativos que:
- Tenha **alto retorno esperado**
- Tenha **baixo risco** (considerando a covariância entre os ativos)
- Respeite **restrições de alocação realistas**, como escolher **somente K ativos**

---

####  **Entendendo as Variáveis**

Vamos usar um exemplo com **4 ativos**:

1. **Apple (AAPL)**
2. **Google (GOOGL)**
3. **Amazon (AMZN)**
4. **Tesouro Direto (TD)** (renda fixa)

Para cada ativo nós temos :

$$
\mu_i = \text{retorno médio anual esperado do ativo } i \\
\sigma_i = \text{desvio padrão (volatilidade) do ativo } i \\
\rho_{i,j} = \text{correlação entre os ativos } i \text{ e } j \\
w_i = \text{peso (proporção do capital) investido no ativo } i
$$

Onde a soma dos pesos deve ser 100%:

$$
\sum_{i=1}^{n} w_i = 1
$$



| Ativo  | Retorno Esperado (μ) | Desvio Padrão (σ) |
|--------|-----------------------|--------------------|
| AAPL   | 0.12                  | 0.20               |
| GOOGL  | 0.10                  | 0.18               |
| AMZN   | 0.14                  | 0.25               |
| TD     | 0.05                  | 0.05               |

Correlação entre os ativos:

| Par de Ativos     | Correlação (ρ) |
|-------------------|----------------|
| AAPL & GOOGL      | 0.80           |
| AAPL & AMZN       | 0.75           |
| AAPL & TD         | 0.10           |
| GOOGL & AMZN      | 0.65           |
| GOOGL & TD        | 0.15           |
| AMZN & TD         | 0.20           |

---

####  **Passo a Passo: Construção da Matriz de Covariância**

A matriz de covariância é calculada com:

$$
\Sigma_{i,j} = \rho_{i,j} \cdot \sigma_i \cdot \sigma_j
$$

Substituindo os valores:

$$
\Sigma_{\text{AAPL, AAPL}} = 0.20^2 = 0.0400 \\
\Sigma_{\text{AAPL, GOOGL}} = 0.80 \cdot 0.20 \cdot 0.18 = 0.0288 \\
\Sigma_{\text{AAPL, AMZN}} = 0.75 \cdot 0.20 \cdot 0.25 = 0.0375 \\
\Sigma_{\text{AAPL, TD}} = 0.10 \cdot 0.20 \cdot 0.05 = 0.0010 \\
\Sigma_{\text{GOOGL, GOOGL}} = 0.18^2 = 0.0324 \\
\Sigma_{\text{GOOGL, AMZN}} = 0.65 \cdot 0.18 \cdot 0.25 = 0.02925 \\
\Sigma_{\text{GOOGL, TD}} = 0.15 \cdot 0.18 \cdot 0.05 = 0.00135 \\
\Sigma_{\text{AMZN, AMZN}} = 0.25^2 = 0.0625 \\
\Sigma_{\text{AMZN, TD}} = 0.20 \cdot 0.25 \cdot 0.05 = 0.0025 \\
\Sigma_{\text{TD, TD}} = 0.05^2 = 0.0025
$$

A matriz de covariância final será:

|         | AAPL   | GOOGL  | AMZN   | TD     |
|---------|--------|--------|--------|--------|
| **AAPL**  | 0.0400 | 0.0288 | 0.0375 | 0.0010 |
| **GOOGL** | 0.0288 | 0.0324 | 0.0293 | 0.0014 |
| **AMZN**  | 0.0375 | 0.0293 | 0.0625 | 0.0025 |
| **TD**    | 0.0010 | 0.0014 | 0.0025 | 0.0025 |

---

#### **Passo a Passo: Cálculo do Retorno Esperado**

Exemplo de alocação:

$$
w_{\text{AAPL}} = 0.3, \quad w_{\text{GOOGL}} = 0.2, \quad w_{\text{AMZN}} = 0.4, \quad w_{\text{TD}} = 0.1
$$

Com isso:

$$
E[R_p] = (0.3 \cdot 0.12) + (0.2 \cdot 0.10) + (0.4 \cdot 0.14) + (0.1 \cdot 0.05) = 0.117 \Rightarrow 11.7\%
$$

---

#### **Passo a Passo: Cálculo do Risco com a Matriz de Covariância**

$$
\sigma_p^2 = \mathbf{w}^T \cdot \Sigma \cdot \mathbf{w}
$$

Substituindo a matriz e o vetor de pesos, temos:

$$
\sigma_p^2 = 
(0.3, 0.2, 0.4, 0.1)
\begin{bmatrix}
0.0400 & 0.0288 & 0.0375 & 0.0010 \\
0.0288 & 0.0324 & 0.0293 & 0.0014 \\
0.0375 & 0.0293 & 0.0625 & 0.0025 \\
0.0010 & 0.0014 & 0.0025 & 0.0025
\end{bmatrix}
\begin{bmatrix}
0.3 \\
0.2 \\
0.4 \\
0.1
\end{bmatrix}
$$

Resultado:

$$
\sigma_p^2 \approx 0.03371 \quad \Rightarrow \quad \sigma_p \approx 18.36\%
$$

---

####  **Passo a Passo: Cálculo do Índice de Sharpe**

Assumindo taxa livre de risco \( R_f = 3\% = 0.03 \):

$$
SR = \frac{E[R_p] - R_f}{\sigma_p} = \frac{0.117 - 0.03}{0.1836} \approx 0.474
$$

---

#### **Restrição de Cardinalidade (K ativos)**

Na prática, é comum limitar o número de ativos no portfólio (ex: no máximo 10). Isso evita carteiras com muitos ativos irrelevantes.

Como o framework `CUSTOMHyS` trabalha apenas com variáveis contínuas, utilizaremos uma **heurística**:

- Geramos um vetor contínuo de pesos.
- Selecionamos os **K ativos com maiores pesos**.
- Zeros nos demais, e normalizamos os K pesos selecionados para somar 1.

---

#### **Fronteira Eficiente e Avaliação das Heurísticas**

A **Fronteira Eficiente Não Restrita (UEF)** representa todas as combinações de portfólio que **maximizam o retorno para um dado nível de risco** ou **minimizam o risco para um dado retorno**, **sem restrições de cardinalidade**.

No artigo de Chang et al. (2000), essa fronteira foi obtida por métodos exatos de otimização convexa e depois **salva em arquivos como `portef1`, `portef2` etc.** com pares 
$$
(\mu, \sigma^2)
$$
 para permitir **comparação com soluções heurísticas**.

Para avaliar a qualidade de uma solução com restrição de cardinalidade (obtida por heurística), os autores projetaram essa solução sobre a UEF. Isso foi feito por meio de interpolação linear entre os pontos da fronteira eficiente, permitindo encontrar a solução teórica mais próxima que apresenta o mesmo nível de risco ou retorno.
---

####  **O que é a Fronteira Eficiente?**

A Fronteira Eficiente é o **conjunto de portfólios ótimos**, ou seja, aqueles que:
- **Têm o menor risco possível** para um dado nível de retorno
- **Têm o maior retorno possível** para um dado nível de risco

Ela é representada graficamente por uma **curva convexa ascendente** no plano **risco × retorno**.

Imagine um gráfico com:
- Eixo X = risco (desvio padrão)
- Eixo Y = retorno esperado

A Fronteira Eficiente é a **borda superior da nuvem de pontos possíveis**, formando uma curva como essa:
#####  **Exemplo Prático**

Vamos supor que temos 1000 combinações aleatórias de portfólios feitos a partir dos ativos:
- AAPL (12%, 20%)
- GOOGL (10%, 18%)
- AMZN (14%, 25%)
- TD (5%, 5%)

Calculamos o retorno e risco de cada portfólio e traçamos todos esses pontos no plano \((\sigma, \mu)\). A Fronteira Eficiente será formada pelos **pontos mais ao norte e à esquerda** da nuvem.

Essa curva pode ser calculada resolvendo uma sequência de problemas de otimização para diferentes níveis de retorno (ou diferentes pesos \(\lambda\)). Quanto mais pontos usarmos, mais suave e precisa será a curva.

<img src=image.png alt="Fronteira Eficiente" width="45%"/>

---


####  **Métrica de Avaliação das Heurísticas**

A partir da curva UEF, os autores do artigo definiram as métricas:

- **Erro percentual na direção do risco**:

$$
\text{Erro}_{\text{risco}} = 100 \times \frac{\sigma^* - \sigma^{**}}{\sigma^{**}}
$$

- **Erro percentual na direção do retorno**:

$$
\text{Erro}_{\text{retorno}} = 100 \times \frac{\mu^* - \mu^{**}}{\mu^{**}}
$$

Onde:

$$
\begin{aligned}
(\mu^*, \sigma^*) &\text{ — solução encontrada pela heurística} \\
(\mu^{**}, \sigma^{**}) &\text{ — projeção correspondente na UEF}
\end{aligned}
$$

A **métrica final** adotada é o menor dos dois erros:

$$
\text{Erro final} = \min(\text{Erro}_{\text{risco}}, \text{Erro}_{\text{retorno}})
$$

Essa abordagem permite **comparar diretamente** o desempenho das heurísticas contra a fronteira ideal de mercado — uma métrica que é ao mesmo tempo quantitativa, interpretável e prática para aplicações científicas.

---

Essa abordagem nos permite **simular o comportamento do problema original com restrição de cardinalidade**, usando apenas variáveis contínuas. A próxima seção demonstrará isso na prática.

### 📊 **Seção 2: Resolvendo o problema com o customhys**

#### Instalando o package e baixando do github
 Utilize caso não esteja em um ambiente com o package instalado, como o google colab

In [1]:
# Clonar rep
# !git clone https://github.com/jcrvz/customhys.git .
# Instalar as dependências
# !pip install -r requirements.txt

# Instalar o CUSTOMHyS como pacote
# !pip install .
# %cd customhys
# %cd customhys

#### Função para ler instâncias OR-Library
Funções que leem instâncias que estão no formato OR-Library para o problema do portfólio single period

In [ ]:
import numpy as np
import pandas as pd
from IPython.display import display



def read_or_library_instance(filepath):
    """
    Lê um arquivo de instância da OR-Library (ex: port1.txt) e retorna:
    - número de ativos
    - retornos esperados (μ_i)
    - desvios padrão (σ_i)
    - matriz de correlação (ρ_{i,j})
    - matriz de covariância (Σ)
    - dataframe da covariância para visualização
    """

    # Abre e lê todas as linhas do arquivo
    with open(filepath, 'r') as file:
        lines = file.readlines()

    # Número total de ativos financeiros disponíveis na instância
    n_assets = int(lines[0].strip())

    # Lê os retornos esperados e os desvios padrão (μ_i e σ_i)
    returns = []
    std_devs = []
    for i in range(1, n_assets + 1):
        mu, sigma = map(float, lines[i].strip().split())
        returns.append(mu)
        std_devs.append(sigma)

    # Inicializa a matriz de correlação com 1's na diagonal principal
    corr_matrix = np.eye(n_assets)

    # Lê os pares de ativos e suas respectivas correlações ρ_{i,j}
    for line in lines[n_assets + 1:]:
        i, j, rho = line.strip().split()
        i, j = int(i) - 1, int(j) - 1  # Corrige índice (de 1-based para 0-based)
        rho = float(rho)
        corr_matrix[i][j] = rho
        corr_matrix[j][i] = rho  # Simetria da matriz

    # Constrói a matriz de covariância Σ com:
    # Σ_{i,j} = ρ_{i,j} * σ_i * σ_j
    sigma_array = np.array(std_devs)
    cov_matrix = np.outer(sigma_array, sigma_array) * corr_matrix

    # Cria um DataFrame para visualização fácil da matriz de covariância
    df_cov = pd.DataFrame(
        cov_matrix,
        columns=[f"Asset {i+1}" for i in range(n_assets)],
        index=[f"Asset {i+1}" for i in range(n_assets)]
    )

    # Retorna um dicionário com todos os dados necessários
    return {
        "n_assets": n_assets,
        "returns": np.array(returns),         # Vetor de retornos esperados μ_i
        "std_devs": np.array(std_devs),       # Vetor de desvios padrão σ_i
        "corr_matrix": corr_matrix,           # Matriz de correlação ρ_{i,j}
        "cov_matrix": cov_matrix,             # Matriz de covariância Σ
        "df_cov": df_cov                      # DataFrame para visualização
    }

In [7]:
# Lê o arquivo port1 para testar
instance_data = read_or_library_instance("port1.txt")

print("\nMatriz de Covariância\n")
display(instance_data["df_cov"].round(5))  # Arredondando para facilitar a leitura

Matriz de Covariância

,Asset 1,Asset 2,Asset 3,Asset 4,Asset 5,Asset 6,Asset 7,Asset 8,Asset 9,Asset 10,...,Asset 22,Asset 23,Asset 24,Asset 25,Asset 26,Asset 27,Asset 28,Asset 29,Asset 30,Asset 31
Asset 1,0.00187,0.00098,0.00133,0.00137,0.00100,0.00163,0.00137,0.00124,0.00088,0.00147,...,0.00089,0.00133,0.00151,0.00162,0.00061,0.00140,0.00041,0.00084,0.00081,0.00082
Asset 2,0.00098,0.00162,0.00104,0.00103,0.00130,0.00113,0.00108,0.00101,0.00092,0.00107,...,0.00083,0.00107,0.00120,0.00134,0.00064,0.00115,0.00037,0.00080,0.00079,0.00072
Asset 3,0.00133,0.00104,0.00171,0.00141,0.00097,0.00155,0.00140,0.00128,0.00111,0.00144,...,0.00094,0.00140,0.00154,0.00169,0.00057,0.00146,0.00043,0.00092,0.00089,0.00087
Asset 4,0.00137,0.00103,0.00141,0.00202,0.00118,0.00171,0.00156,0.00144,0.00123,0.00153,...,0.00102,0.00170,0.00182,0.00177,0.00065,0.00152,0.00049,0.00096,0.00095,0.00092
Asset 5,0.00100,0.00130,0.00097,0.00118,0.00478,0.00127,0.00121,0.00116,0.00117,0.00106,...,0.00071,0.00130,0.00118,0.00138,0.00055,0.00130,0.00042,0.00064,0.00088,0.00063
Asset 6,0.00163,0.00113,0.00155,0.00171,0.00127,0.00288,0.00174,0.00156,0.00124,0.00186,...,0.00117,0.00175,0.00192,0.00194,0.00072,0.00174,0.00068,0.00111,0.00107,0.00102
Asset 7,0.00137,0.00108,0.00140,0.00156,0.00121,0.00174,0.00217,0.00146,0.00114,0.00173,...,0.00108,0.00157,0.00179,0.00179,0.00083,0.00179,0.00064,0.00104,0.00099,0.00103
Asset 8,0.00124,0.00101,0.00128,0.00144,0.00116,0.00156,0.00146,0.00207,0.00127,0.00138,...,0.00101,0.00167,0.00155,0.00162,0.00063,0.00148,0.00052,0.00101,0.00094,0.00095
Asset 9,0.00088,0.00092,0.00111,0.00123,0.00117,0.00124,0.00114,0.00127,0.00288,0.00106,...,0.00071,0.00127,0.00121,0.00129,0.00045,0.00120,0.00048,0.00082,0.00071,0.00082
Asset 10,0.00147,0.00107,0.00144,0.00153,0.00106,0.00186,0.00173,0.00138,0.00106,0.00220,...,0.00111,0.00152,0.00187,0.00179,0.00061,0.00165,0.00068,0.00107,0.00098,0.00099
Asset 11,0.00115,0.00081,0.00112,0.00118,0.00070,0.00148,0.00138,0.00128,0.00102,0.00147,...,0.00108,0.00125,0.00155,0.00157,0.00069,0.00134,0.00044,0.00095,0.00092,0.00087
Asset 12,0.00119,0.00102,0.00112,0.00136,0.00147,0.00143,0.00133,0.00131,0.00102,0.00122,...,0.00091,0.00138,0.00147,0.00149,0.00066,0.00131,0.00045,0.00089,0.00095,0.00088
Asset 13,0.00082,0.00109,0.00087,0.00100,0.00115,0.00097,0.00107,0.00100,0.00087,0.00101,...,0.00082,0.00098,0.00121,0.00115,0.00048,0.00104,0.00042,0.00093,0.00066,0.00072
Asset 14,0.00137,0.00114,0.00143,0.00149,0.00125,0.00170,0.00161,0.00147,0.00123,0.00160,...,0.00127,0.00157,0.00165,0.00180,0.00067,0.00156,0.00040,0.00103,0.00106,0.00096
Asset 15,0.00085,0.00081,0.00089,0.00088,0.00084,0.00097,0.00103,0.00095,0.00090,0.00098,...,0.00089,0.00096,0.00109,0.00114,0.00041,0.00098,0.00044,0.00067,0.00076,0.00080
Asset 16,0.00072,0.00067,0.00079,0.00084,0.00073,0.00091,0.00090,0.00084,0.00071,0.00097,...,0.00080,0.00085,0.00104,0.00108,0.00047,0.00093,0.00039,0.00067,0.00064,0.00070
Asset 17,0.00090,0.00063,0.00082,0.00100,0.00084,0.00123,0.00104,0.00089,0.00084,0.00104,...,0.00077,0.00099,0.00117,0.00112,0.00050,0.00103,0.00050,0.00067,0.00070,0.00060
Asset 18,0.00117,0.00103,0.00119,0.00135,0.00119,0.00142,0.00134,0.00128,0.00116,0.00130,...,0.00106,0.00139,0.00147,0.00155,0.00073,0.00139,0.00050,0.00086,0.00104,0.00092
Asset 19,0.00119,0.00133,0.00126,0.00141,0.00225,0.00158,0.00147,0.00130,0.00118,0.00145,...,0.00113,0.00139,0.00153,0.00173,0.00064,0.00152,0.00045,0.00090,0.00104,0.00093
Asset 20,0.00142,0.00104,0.00149,0.00180,0.00107,0.00181,0.00170,0.00145,0.00124,0.00170,...,0.00117,0.00170,0.00198,0.00194,0.00067,0.00163,0.00053,0.00108,0.00106,0.00104
Asset 21,0.00124,0.00101,0.00129,0.00144,0.00098,0.00161,0.00151,0.00149,0.00114,0.00149,...,0.00105,0.00142,0.00166,0.00164,0.00056,0.00147,0.00048,0.00098,0.00106,0.00105
Asset 22,0.00089,0.00083,0.00094,0.00102,0.00071,0.00117,0.00108,0.00101,0.00071,0.00111,...,0.00145,0.00107,0.00118,0.00122,0.00056,0.00110,0.00034,0.00080,0.00098,0.00091
Asset 23,0.00133,0.00107,0.00140,0.00170,0.00130,0.00175,0.00157,0.00167,0.00127,0.00152,...,0.00107,0.00208,0.00177,0.00181,0.00061,0.00155,0.00050,0.00103,0.00093,0.00099
Asset 24,0.00151,0.00120,0.00154,0.00182,0.00118,0.00192,0.00179,0.00155,0.00121,0.00187,...,0.00118,0.00177,0.00255,0.00195,0.00066,0.00174,0.00060,0.00123,0.00104,0.00103
Asset 25,0.00162,0.00134,0.00169,0.00177,0.00138,0.00194,0.00179,0.00162,0.00129,0.00179,...,0.00122,0.00181,0.00195,0.00284,0.00083,0.00185,0.00062,0.00114,0.00113,0.00107
Asset 26,0.00061,0.00064,0.00057,0.00065,0.00055,0.00072,0.00083,0.00063,0.00045,0.00061,...,0.00056,0.00061,0.00066,0.00083,0.00207,0.00078,0.00023,0.00052,0.00055,0.00049
Asset 27,0.00140,0.00115,0.00146,0.00152,0.00130,0.00174,0.00179,0.00148,0.00120,0.00165,...,0.00110,0.00155,0.00174,0.00185,0.00078,0.00230,0.00059,0.00101,0.00101,0.00106
Asset 28,0.00041,0.00037,0.00043,0.00049,0.00042,0.00068,0.00064,0.00052,0.00048,0.00068,...,0.00034,0.00050,0.00060,0.00062,0.00023,0.00059,0.00130,0.00048,0.00027,0.00034
Asset 29,0.00084,0.00080,0.00092,0.00096,0.00064,0.00111,0.00104,0.00101,0.00082,0.00107,...,0.00080,0.00103,0.00123,0.00114,0.00052,0.00101,0.00048,0.00129,0.00067,0.00070
Asset 30,0.00081,0.00079,0.00089,0.00095,0.00088,0.00107,0.00099,0.00094,0.00071,0.00098,...,0.00098,0.00093,0.00104,0.00113,0.00055,0.00101,0.00027,0.00067,0.00135,0.00088
Asset 31,0.00082,0.00072,0.00087,0.00092,0.00063,0.00102,0.00103,0.00095,0.00082,0.00099,...,0.00091,0.00099,0.00103,0.00107,0.00049,0.00106,0.00034,0.00070,0.00088,0.00159

#### Criando função de avaliação

In [22]:
def portfolio_evaluation(weights, instance_data, k=None, risk_free_rate=0.03):
    """
    Avaliação de um portfólio com base em pesos contínuos, incluindo restrição de cardinalidade.
    
    Parâmetros:
    - weights: vetor de alocação contínua (não necessariamente normalizado)
    - instance_data: dicionário com retornos e matriz de covariância
    - k: número máximo de ativos permitidos (cardinalidade)
    - risk_free_rate: taxa livre de risco

    Retorna:
    - resultado da otimização (valor negativo do Sharpe ratio)
    - histórico da execução contendo retorno, risco, sharpe e ativos selecionados
    """
    n = instance_data["n_assets"]
    returns = instance_data["returns"]
    cov = instance_data["cov_matrix"]

    weights = np.array(weights)

    # Aplica restrição de cardinalidade se necessário
    if k is not None and k < n:
        top_indices = np.argsort(weights)[-k:]
        mask = np.zeros_like(weights)
        mask[top_indices] = 1
        weights = weights * mask
        weights /= weights.sum() if weights.sum() != 0 else 1
    else:
        weights /= weights.sum() if weights.sum() != 0 else 1

    # Calcula retorno esperado
    expected_return = np.dot(weights, returns)

    # Calcula risco (desvio padrão)
    variance = np.dot(weights, np.dot(cov, weights))
    risk = np.sqrt(variance)

    # Calcula índice de Sharpe
    sharpe = (expected_return - risk_free_rate) / risk if risk > 0 else -1e6

    # Cria dicionário com os dados da execução
    execution_log = {
        "weights": weights.copy(),
        "selected_assets": np.where(weights > 0)[0].tolist(),
        "expected_return": expected_return,
        "risk": risk,
        "sharpe": sharpe
    }

    return -sharpe, execution_log  # Retorna resultado negativo para minimizar + log completo

##### Testando no portifólio de 4 ativos

In [47]:

# Exemplo de teste rápido
from_port1 = {
    "n_assets": 4,
    "returns": np.array([0.12, 0.10, 0.14, 0.05]),
    "cov_matrix": np.array([
        [0.0400, 0.0288, 0.0375, 0.0010],
        [0.0288, 0.0324, 0.0293, 0.0014],
        [0.0375, 0.0293, 0.0625, 0.0025],
        [0.0010, 0.0014, 0.0025, 0.0025]
    ])
}

# Executa a função
resultado, log = portfolio_evaluation([0.3, 0.2, 0.4, 0.1], from_port1, k=2, risk_free_rate=0.03)

# Visualiza
df_log = pd.DataFrame([log])
display(df_log[["weights", "selected_assets", "expected_return", "risk", "sharpe"]].round(5))

,weights,selected_assets,expected_return,risk,sharpe
0,"[0.4285714285714286, 0.0, 0.5714285714285715, ...","[0, 2]",0.13143,0.21476,0.47228

#### Função para criar problema no formato que a hyperheuristica aceita, utilizando os probelmas já definidos acima

In [48]:
def configure_problem(instance_data, k=None, risk_free_rate=0.03):
    """
    Configura o problema no formato aceito pelo CUSTOMHyS.
    
    Parâmetros:
    - instance_data: dicionário retornado por read_or_library_instance()
    - k: restrição de cardinalidade (número máximo de ativos)
    - risk_free_rate: taxa livre de risco

    Retorna:
    - dicionário com as chaves esperadas por CUSTOMHyS
    """
    n = instance_data["n_assets"]
    lower_bounds = [0.0] * n
    upper_bounds = [1.0] * n

    return {
        "function": lambda weights: portfolio_evaluation(weights, instance_data, k=k, risk_free_rate=risk_free_rate)[0],
        "is_constrained": True,
        "boundaries": (lower_bounds, upper_bounds)
    }

##### Exemplo de uso

In [49]:
# Carrega os dados da instância da OR-Library
instance_data = read_or_library_instance("port1.txt")

# Prepara o problema para o CUSTOMHyS com restrição de 10 ativos
problem_config = configure_problem(instance_data, k=10)

# Verifica estrutura
import json
print(json.dumps(problem_config, indent=2, default=str))

{
  "function": "<function configure_problem.<locals>.<lambda> at 0x00000253C6AE74C0>",
  "is_constrained": true,
  "boundaries": [
    [
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0
    ],
    [
      1.0,
      1.0,
      1.0,
      1.0,
      1.0,
      1.0,
      1.0,
      1.0,
      1.0,
      1.0,
      1.0,
      1.0,
      1.0,
      1.0,
      1.0,
      1.0,
      1.0,
      1.0,
      1.0,
      1.0,
      1.0,
      1.0,
      1.0,
      1.0,
      1.0,
      1.0,
      1.0,
      1.0,
      1.0,
      1.0,
      1.0
    ]
  ]
}

#### Configração de parametros para a hyperheuristica

In [50]:
# 🔹 Configuração dos parâmetros da Hyper-Heurística
hh_config = {
    "cardinality": 10,  # Máximo de operadores na sequência
    "cardinality_min": 1,  # Mínimo de operadores na sequência
    "num_iterations": 100,  # Número de iterações
    "num_agents": 30,  # Tamanho da população
    "as_mh": False,  # Usa a sequência de HH como uma metaheurística completa?
    "num_replicas": 20,  # Número de réplicas por MH
    "num_steps": 100,  # Número de tentativas por passo da HH
    "stagnation_percentage": 0.40,  # Percentual de estagnação para controle
    "max_temperature": 1,  # Temperatura inicial (Simulated Annealing)
    "min_temperature": 1e-6,  # Temperatura mínima (Simulated Annealing)
    "cooling_rate": 1e-3,  # Taxa de resfriamento (Simulated Annealing)
    "temperature_scheme": "fast",  # Esquema de temperatura
    "acceptance_scheme": "exponential",  # Critério de aceitação de soluções
    "allow_weight_matrix": True,  # Permite matriz de pesos
    "trial_overflow": False,  # Política de overflow de tentativas
    "repeat_operators": True,  # Permite repetição de operadores na sequência
    "verbose": True,  # Exibir logs e progresso
    "learning_portion": 0.5,  # Percentual de aprendizado das sequências
    "solver": "dynamic",  # Tipo de solver
}

##### Confirmando configurações

In [51]:
import json

print("\n🔍 [LOG] Estrutura do Problema antes da Hyper-Heurística:")
print(json.dumps(problem_config, indent=4, default=str))  # Imprime o dicionário do problema de forma legível
print("\n🔍 [LOG] Configuração da Hyper-Heurística:")
print(json.dumps(hh_config, indent=4, default=str))

🔍 [LOG] Estrutura do Problema antes da Hyper-Heurística:
{
    "function": "<function configure_problem.<locals>.<lambda> at 0x00000253C6AE74C0>",
    "is_constrained": true,
    "boundaries": [
        [
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0
        ],
        [
            1.0,
            1.0,
            1.0,
            1.0,
            1.0,
            1.0,
            1.0,
            1.0,
            1.0,
            1.0,
            1.0,
            1.0,
            1.0,
            1.0,
            1.0,
            1.0,
            1.0,
            1.0,
            1.0,
            1.0,
            1.0,
            1.0,
            1.0,
            1.0,
            1.0,
            1.0,
            1.0,
            1.0,
            1.0,
            1.0,
            1.0
        ]
    ]
}

🔍 [LOG] Configuração da Hyper-Heurística:
{
    "cardinality": 10,
    "cardinality_min": 1,
    "num_iterations": 100,
    "num_agents": 30,
    "as_mh": false,
    "num_replicas": 20,
    "num_steps": 100,
    "stagnation_percentage": 0.4,
    "max_temperature": 1,
    "min_temperature": 1e-06,
    "cooling_rate": 0.001,
    "temperature_scheme": "fast",
    "acceptance_scheme": "exponential",
    "allow_weight_matrix": true,
    "trial_overflow": false,
    "repeat_operators": true,
    "verbose": true,
    "learning_portion": 0.5,
    "solver": "dynamic"
}

#### Executando a hyperheuristica

In [53]:
from customhys.hyperheuristic import Hyperheuristic

# 🔹 Criar a instância da Hyper-Heurística
hh = Hyperheuristic(heuristic_space='default.txt', problem=problem_config, parameters=hh_config)

# 🔹 Executar a otimização
print("\n🚀 [LOG] Iniciando execução da Hyper-Heurística...\n")

result = hh.solve()  # Executa a otimização

print("\n🔍 [LOG] Resultado da Hyper-Heurística:", result)

🚀 [LOG] Iniciando execução da Hyper-Heurística...

Num_agents: 30, Num_iterations: 1, Initial_scheme: random
Verbose: False
 :: Rep:   1, Step:   1, Trial:   0, SO: swarm_dynamic & gree          , currPerf: 6.77e-01, candPerf: 6.77e-01 which: entered    +
 :: Rep:   1, Step:   2, Trial:   0, SO: local_random_walk & prob      , currPerf: 6.77e-01, candPerf: 6.77e-01 which: entered    +
 :: Rep:   1, Step:   3, Trial:   0, SO: gravitational_search & all    , currPerf: 6.77e-01, candPerf: 6.77e-01 which: entered
 :: Rep:   1, Step:   3, Trial:   1, SO: firefly_dynamic & metr        , currPerf: 6.77e-01, candPerf: 6.77e-01 which: entered
 :: Rep:   1, Step:   3, Trial:   2, SO: genetic_crossover & metr      , currPerf: 6.77e-01, candPerf: 6.74e-01 which: entered    +
 :: Rep:   1, Step:   4, Trial:   0, SO: random_sample & prob          , currPerf: 6.74e-01, candPerf: 6.58e-01 which: entered    +
 :: Rep:   1, Step:   5, Trial:   0, SO: genetic_crossover & prob      , currPerf: 6.58e-01, candPerf: 6.55e-01 which: entered    +
 :: Rep:   1, Step:   6, Trial:   0, SO: random_search & prob          , currPerf: 6.55e-01, candPerf: 6.54e-01 which: entered    +
 :: Rep:   1, Step:   7, Trial:   0, SO: random_flight & prob          , currPerf: 6.54e-01, candPerf: 6.54e-01 which: entered
 :: Rep:   1, Step:   7, Trial:   1, SO: swarm_dynamic & all           , currPerf: 6.54e-01, candPerf: 6.54e-01 which: entered    +
 :: Rep:   1, Step:   8, Trial:   0, SO: random_flight & prob          , currPerf: 6.54e-01, candPerf: 6.54e-01 which: entered
 :: Rep:   1, Step:   8, Trial:   1, SO: local_random_walk & gree      , currPerf: 6.54e-01, candPerf: 6.39e-01 which: entered    +
 :: Rep:   1, Step:   9, Trial:   0, SO: genetic_mutation & prob       , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:   9, Trial:   1, SO: swarm_dynamic & metr          , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:   9, Trial:   2, SO: differential_mutation & gree  , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:   9, Trial:   3, SO: random_search & prob          , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered    +
 :: Rep:   1, Step:  10, Trial:   0, SO: differential_mutation & gree  , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  10, Trial:   1, SO: swarm_dynamic & all           , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  10, Trial:   2, SO: genetic_crossover & all       , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  10, Trial:   3, SO: genetic_crossover & metr      , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  10, Trial:   4, SO: swarm_dynamic & metr          , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  10, Trial:   5, SO: genetic_mutation & gree       , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  10, Trial:   6, SO: firefly_dynamic & all         , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  10, Trial:   7, SO: differential_mutation & gree  , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered    +
 :: Rep:   1, Step:  11, Trial:   0, SO: swarm_dynamic & gree          , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  11, Trial:   1, SO: genetic_crossover & prob      , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  11, Trial:   2, SO: swarm_dynamic & gree          , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  11, Trial:   3, SO: swarm_dynamic & metr          , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  11, Trial:   4, SO: firefly_dynamic & all         , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered    +
 :: Rep:   1, Step:  12, Trial:   0, SO: genetic_crossover & gree      , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  12, Trial:   1, SO: genetic_crossover & prob      , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  12, Trial:   2, SO: differential_mutation & gree  , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  12, Trial:   3, SO: local_random_walk & all       , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  12, Trial:   4, SO: random_search & all           , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  12, Trial:   5, SO: random_search & prob          , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered    +
 :: Rep:   1, Step:  13, Trial:   0, SO: genetic_mutation & all        , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  13, Trial:   1, SO: genetic_crossover & gree      , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  13, Trial:   2, SO: genetic_mutation & prob       , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered    +
 :: Rep:   1, Step:  14, Trial:   0, SO: genetic_crossover & all       , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  14, Trial:   1, SO: differential_mutation & prob  , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered    +
 :: Rep:   1, Step:  15, Trial:   0, SO: local_random_walk & metr      , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered    +
 :: Rep:   1, Step:  16, Trial:   0, SO: genetic_crossover & prob      , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  16, Trial:   1, SO: genetic_crossover & gree      , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  16, Trial:   2, SO: firefly_dynamic & prob        , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  16, Trial:   3, SO: random_flight & metr          , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered    +
 :: Rep:   1, Step:  17, Trial:   0, SO: genetic_crossover & metr      , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  17, Trial:   1, SO: swarm_dynamic & prob          , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  17, Trial:   2, SO: swarm_dynamic & metr          , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  17, Trial:   3, SO: genetic_crossover & prob      , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  17, Trial:   4, SO: genetic_crossover & prob      , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  17, Trial:   5, SO: firefly_dynamic & all         , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  17, Trial:   6, SO: genetic_mutation & prob       , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  17, Trial:   7, SO: differential_mutation & all   , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  17, Trial:   8, SO: genetic_crossover & all       , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  17, Trial:   9, SO: genetic_mutation & metr       , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  17, Trial:  10, SO: random_flight & all           , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  17, Trial:  11, SO: genetic_crossover & metr      , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  17, Trial:  12, SO: differential_mutation & prob  , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered    +
 :: Rep:   1, Step:  18, Trial:   0, SO: genetic_crossover & prob      , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  18, Trial:   1, SO: differential_mutation & metr  , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  18, Trial:   2, SO: differential_mutation & prob  , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  18, Trial:   3, SO: genetic_crossover & all       , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  18, Trial:   4, SO: swarm_dynamic & metr          , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  18, Trial:   5, SO: local_random_walk & gree      , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered    +
 :: Rep:   1, Step:  19, Trial:   0, SO: genetic_crossover & prob      , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  19, Trial:   1, SO: local_random_walk & prob      , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  19, Trial:   2, SO: gravitational_search & prob   , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  19, Trial:   3, SO: swarm_dynamic & gree          , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  19, Trial:   4, SO: genetic_crossover & prob      , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  19, Trial:   5, SO: differential_mutation & gree  , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  19, Trial:   6, SO: firefly_dynamic & gree        , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered    +
 :: Rep:   1, Step:  20, Trial:   0, SO: swarm_dynamic & prob          , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  20, Trial:   1, SO: genetic_crossover & all       , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  20, Trial:   2, SO: differential_mutation & all   , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  20, Trial:   3, SO: gravitational_search & metr   , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  20, Trial:   4, SO: local_random_walk & all       , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  20, Trial:   5, SO: differential_mutation & metr  , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered    +
 :: Rep:   1, Step:  21, Trial:   0, SO: genetic_crossover & gree      , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  21, Trial:   1, SO: genetic_crossover & prob      , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  21, Trial:   2, SO: spiral_dynamic & all          , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  21, Trial:   3, SO: random_sample & gree          , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  21, Trial:   4, SO: genetic_crossover & all       , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  21, Trial:   5, SO: local_random_walk & all       , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  21, Trial:   6, SO: genetic_crossover & all       , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  21, Trial:   7, SO: genetic_crossover & metr      , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered    +
 :: Rep:   1, Step:  22, Trial:   0, SO: differential_mutation & gree  , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  22, Trial:   1, SO: genetic_crossover & metr      , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  22, Trial:   2, SO: local_random_walk & all       , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  22, Trial:   3, SO: swarm_dynamic & metr          , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  22, Trial:   4, SO: spiral_dynamic & gree         , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  22, Trial:   5, SO: genetic_crossover & metr      , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  22, Trial:   6, SO: genetic_crossover & gree      , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  22, Trial:   7, SO: random_search & all           , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  22, Trial:   8, SO: spiral_dynamic & gree         , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered    +
 :: Rep:   1, Step:  23, Trial:   0, SO: differential_mutation & prob  , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  23, Trial:   1, SO: swarm_dynamic & prob          , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered    +
 :: Rep:   1, Step:  24, Trial:   0, SO: genetic_crossover & metr      , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  24, Trial:   1, SO: differential_mutation & all   , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  24, Trial:   2, SO: genetic_crossover & gree      , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  24, Trial:   3, SO: differential_mutation & all   , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  24, Trial:   4, SO: genetic_crossover & all       , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered    +
 :: Rep:   1, Step:  25, Trial:   0, SO: differential_mutation & prob  , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  25, Trial:   1, SO: genetic_crossover & gree      , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  25, Trial:   2, SO: local_random_walk & gree      , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered    +
 :: Rep:   1, Step:  26, Trial:   0, SO: differential_mutation & metr  , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered    +
 :: Rep:   1, Step:  27, Trial:   0, SO: genetic_crossover & prob      , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered    +
 :: Rep:   1, Step:  28, Trial:   0, SO: firefly_dynamic & all         , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  28, Trial:   1, SO: swarm_dynamic & gree          , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  28, Trial:   2, SO: genetic_crossover & all       , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  28, Trial:   3, SO: genetic_crossover & gree      , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  28, Trial:   4, SO: genetic_crossover & all       , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  28, Trial:   5, SO: local_random_walk & metr      , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  28, Trial:   6, SO: swarm_dynamic & prob          , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered    +
 :: Rep:   1, Step:  29, Trial:   0, SO: differential_mutation & gree  , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  29, Trial:   1, SO: random_flight & metr          , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  29, Trial:   2, SO: genetic_crossover & prob      , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  29, Trial:   3, SO: swarm_dynamic & metr          , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  29, Trial:   4, SO: genetic_crossover & gree      , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  29, Trial:   5, SO: genetic_crossover & metr      , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  29, Trial:   6, SO: genetic_mutation & prob       , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered    +
 :: Rep:   1, Step:  30, Trial:   0, SO: genetic_crossover & all       , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  30, Trial:   1, SO: random_flight & prob          , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered    +
 :: Rep:   1, Step:  31, Trial:   0, SO: firefly_dynamic & metr        , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  31, Trial:   1, SO: random_flight & metr          , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  31, Trial:   2, SO: random_search & prob          , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  31, Trial:   3, SO: genetic_crossover & metr      , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  31, Trial:   4, SO: firefly_dynamic & metr        , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  31, Trial:   5, SO: swarm_dynamic & prob          , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered    +
 :: Rep:   1, Step:  32, Trial:   0, SO: genetic_crossover & all       , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  32, Trial:   1, SO: local_random_walk & all       , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  32, Trial:   2, SO: genetic_crossover & prob      , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  32, Trial:   3, SO: genetic_crossover & all       , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  32, Trial:   4, SO: swarm_dynamic & gree          , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  32, Trial:   5, SO: genetic_crossover & gree      , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  32, Trial:   6, SO: genetic_crossover & gree      , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  32, Trial:   7, SO: gravitational_search & metr   , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered    +
 :: Rep:   1, Step:  33, Trial:   0, SO: random_flight & prob          , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  33, Trial:   1, SO: genetic_mutation & metr       , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  33, Trial:   2, SO: local_random_walk & gree      , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  33, Trial:   3, SO: random_flight & metr          , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  33, Trial:   4, SO: genetic_crossover & prob      , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  33, Trial:   5, SO: random_search & all           , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  33, Trial:   6, SO: random_flight & gree          , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered    +
 :: Rep:   1, Step:  34, Trial:   0, SO: gravitational_search & gree   , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered    +
 :: Rep:   1, Step:  35, Trial:   0, SO: random_sample & gree          , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  35, Trial:   1, SO: firefly_dynamic & all         , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  35, Trial:   2, SO: random_search & all           , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  35, Trial:   3, SO: random_search & prob          , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  35, Trial:   4, SO: genetic_crossover & all       , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered    +
 :: Rep:   1, Step:  36, Trial:   0, SO: differential_mutation & all   , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  36, Trial:   1, SO: swarm_dynamic & prob          , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  36, Trial:   2, SO: genetic_mutation & all        , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  36, Trial:   3, SO: swarm_dynamic & all           , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  36, Trial:   4, SO: random_flight & gree          , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered
 :: Rep:   1, Step:  36, Trial:   5, SO: genetic_crossover & prob      , currPerf: 6.39e-01, candPerf: 6.39e-01 which: entered    +

d:\Documentos\Projetos\Ufersa\customhys\customhys\population.py:235: RuntimeWarning: invalid value encountered in cast
  self.velocities[agent_id, :] = np.copy(self.previous_velocities[agent_id, :])

 :: Rep:   8, Step:  81, Trial:   1, SO: random_search & all           , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered    +
 :: Rep:   8, Step:  82, Trial:   0, SO: genetic_crossover & all       , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered    +
 :: Rep:   8, Step:  83, Trial:   0, SO: random_sample & metr          , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered    +
 :: Rep:   8, Step:  84, Trial:   0, SO: differential_mutation & prob  , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  84, Trial:   1, SO: random_search & all           , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  84, Trial:   2, SO: genetic_crossover & prob      , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered    +
 :: Rep:   8, Step:  85, Trial:   0, SO: swarm_dynamic & prob          , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  85, Trial:   1, SO: genetic_mutation & prob       , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  85, Trial:   2, SO: differential_mutation & prob  , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  85, Trial:   3, SO: genetic_crossover & prob      , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  85, Trial:   4, SO: genetic_crossover & gree      , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  85, Trial:   5, SO: random_flight & gree          , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  85, Trial:   6, SO: genetic_crossover & metr      , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  85, Trial:   7, SO: genetic_crossover & prob      , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  85, Trial:   8, SO: swarm_dynamic & metr          , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered    +
 :: Rep:   8, Step:  86, Trial:   0, SO: random_flight & prob          , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  86, Trial:   1, SO: spiral_dynamic & gree         , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  86, Trial:   2, SO: spiral_dynamic & prob         , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  86, Trial:   3, SO: genetic_crossover & metr      , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered    +
 :: Rep:   8, Step:  87, Trial:   0, SO: firefly_dynamic & all         , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  87, Trial:   1, SO: genetic_mutation & gree       , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  87, Trial:   2, SO: genetic_crossover & metr      , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  87, Trial:   3, SO: random_flight & all           , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  87, Trial:   4, SO: differential_mutation & prob  , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  87, Trial:   5, SO: central_force_dynamic & all   , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  87, Trial:   6, SO: swarm_dynamic & metr          , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  87, Trial:   7, SO: genetic_crossover & metr      , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered    +
 :: Rep:   8, Step:  88, Trial:   0, SO: random_search & metr          , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered    +
 :: Rep:   8, Step:  89, Trial:   0, SO: swarm_dynamic & prob          , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  89, Trial:   1, SO: genetic_crossover & all       , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  89, Trial:   2, SO: differential_mutation & prob  , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  89, Trial:   3, SO: firefly_dynamic & prob        , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  89, Trial:   4, SO: gravitational_search & all    , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered    +
 :: Rep:   8, Step:  90, Trial:   0, SO: random_flight & gree          , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  90, Trial:   1, SO: genetic_crossover & metr      , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered    +
 :: Rep:   8, Step:  91, Trial:   0, SO: differential_mutation & prob  , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  91, Trial:   1, SO: genetic_crossover & gree      , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered    +
 :: Rep:   8, Step:  92, Trial:   0, SO: genetic_mutation & metr       , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  92, Trial:   1, SO: differential_mutation & prob  , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  92, Trial:   2, SO: swarm_dynamic & prob          , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  92, Trial:   3, SO: random_flight & metr          , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered    +
 :: Rep:   8, Step:  93, Trial:   0, SO: gravitational_search & all    , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  93, Trial:   1, SO: central_force_dynamic & metr  , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  93, Trial:   2, SO: differential_mutation & gree  , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  93, Trial:   3, SO: genetic_crossover & prob      , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  93, Trial:   4, SO: random_search & metr          , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  93, Trial:   5, SO: genetic_crossover & all       , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  93, Trial:   6, SO: genetic_crossover & prob      , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered    +
 :: Rep:   8, Step:  94, Trial:   0, SO: random_flight & prob          , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  94, Trial:   1, SO: swarm_dynamic & gree          , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  94, Trial:   2, SO: genetic_crossover & prob      , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  94, Trial:   3, SO: genetic_crossover & prob      , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  94, Trial:   4, SO: swarm_dynamic & prob          , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered    +
 :: Rep:   8, Step:  95, Trial:   0, SO: differential_mutation & gree  , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  95, Trial:   1, SO: genetic_crossover & gree      , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  95, Trial:   2, SO: genetic_crossover & all       , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered    +
 :: Rep:   8, Step:  96, Trial:   0, SO: swarm_dynamic & gree          , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  96, Trial:   1, SO: genetic_crossover & gree      , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  96, Trial:   2, SO: genetic_mutation & metr       , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  96, Trial:   3, SO: random_flight & prob          , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  96, Trial:   4, SO: spiral_dynamic & prob         , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  96, Trial:   5, SO: genetic_crossover & all       , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  96, Trial:   6, SO: local_random_walk & all       , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  96, Trial:   7, SO: local_random_walk & metr      , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  96, Trial:   8, SO: local_random_walk & gree      , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  96, Trial:   9, SO: random_search & metr          , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  96, Trial:  10, SO: genetic_crossover & metr      , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  96, Trial:  11, SO: swarm_dynamic & gree          , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  96, Trial:  12, SO: local_random_walk & all       , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered    +
 :: Rep:   8, Step:  97, Trial:   0, SO: gravitational_search & metr   , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  97, Trial:   1, SO: swarm_dynamic & prob          , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  97, Trial:   2, SO: spiral_dynamic & all          , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  97, Trial:   3, SO: genetic_mutation & prob       , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  97, Trial:   4, SO: spiral_dynamic & prob         , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  97, Trial:   5, SO: random_flight & gree          , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered    +
 :: Rep:   8, Step:  98, Trial:   0, SO: genetic_crossover & prob      , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  98, Trial:   1, SO: genetic_mutation & prob       , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step:  98, Trial:   2, SO: firefly_dynamic & all         , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered    +
 :: Rep:   8, Step:  99, Trial:   0, SO: firefly_dynamic & gree        , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered    +
 :: Rep:   8, Step: 100, Trial:   0, SO: genetic_crossover & all       , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step: 100, Trial:   1, SO: differential_mutation & prob  , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step: 100, Trial:   2, SO: genetic_crossover & metr      , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered
 :: Rep:   8, Step: 100, Trial:   3, SO: swarm_dynamic & all           , currPerf: 6.12e-01, candPerf: 6.12e-01 which: entered    +

Best fitness: 0.6115035223766309,
Best position: [ 6.58862800e-01  4.89517663e-01 -1.28899893e+00 -4.93349651e+02
  1.64542136e+00 -2.03552750e+01  1.79529144e+00  1.79546419e+02
  7.97909659e-01 -4.75299266e-01  2.09584307e+00  1.03327859e+00
  2.84754183e+05  3.61273996e-01  9.13746825e-01 -2.08627218e+03
  5.90024491e+01 -9.83286914e+01  8.32870912e+01 -4.29964059e-01
 -4.68954708e+01  1.09519462e+00  2.05354522e+00  7.38705469e-01
 -4.46459777e+01 -2.55013817e+00  1.12825728e+00  1.54237861e+00
  1.53369817e+00  1.61661584e+02 -3.22525170e-01]
Num_agents: 30, Num_iterations: 1, Initial_scheme: random
Verbose: False
 :: Rep:   9, Step:   1, Trial:   0, SO: differential_mutation & prob  , currPerf: 6.42e-01, candPerf: 6.42e-01 which: entered
 :: Rep:   9, Step:   1, Trial:   1, SO: genetic_crossover & gree      , currPerf: 6.42e-01, candPerf: 6.42e-01 which: entered    +
 :: Rep:   9, Step:   2, Trial:   0, SO: differential_mutation & prob  , currPerf: 6.42e-01, candPerf: 6.34e-01 which: entered    +
 :: Rep:   9, Step:   3, Trial:   0, SO: random_search & prob          , currPerf: 6.34e-01, candPerf: 6.30e-01 which: entered    +
 :: Rep:   9, Step:   4, Trial:   0, SO: differential_mutation & gree  , currPerf: 6.30e-01, candPerf: 6.30e-01 which: entered
 :: Rep:   9, Step:   4, Trial:   1, SO: local_random_walk & all       , currPerf: 6.30e-01, candPerf: 6.30e-01 which: entered
 :: Rep:   9, Step:   4, Trial:   2, SO: random_search & all           , currPerf: 6.30e-01, candPerf: 6.30e-01 which: entered    +
 :: Rep:   9, Step:   5, Trial:   0, SO: differential_mutation & metr  , currPerf: 6.30e-01, candPerf: 6.30e-01 which: entered
 :: Rep:   9, Step:   5, Trial:   1, SO: genetic_crossover & metr      , currPerf: 6.30e-01, candPerf: 6.30e-01 which: entered    +
 :: Rep:   9, Step:   6, Trial:   0, SO: genetic_crossover & gree      , currPerf: 6.30e-01, candPerf: 6.30e-01 which: entered
 :: Rep:   9, Step:   6, Trial:   1, SO: local_random_walk & metr      , currPerf: 6.30e-01, candPerf: 6.30e-01 which: entered    +
 :: Rep:   9, Step:   7, Trial:   0, SO: differential_mutation & all   , currPerf: 6.30e-01, candPerf: 6.30e-01 which: entered    +
 :: Rep:   9, Step:   8, Trial:   0, SO: genetic_mutation & gree       , currPerf: 6.30e-01, candPerf: 6.30e-01 which: entered
 :: Rep:   9, Step:   8, Trial:   1, SO: random_flight & gree          , currPerf: 6.30e-01, candPerf: 6.30e-01 which: entered
 :: Rep:   9, Step:   8, Trial:   2, SO: genetic_crossover & all       , currPerf: 6.30e-01, candPerf: 6.30e-01 which: entered    +
 :: Rep:   9, Step:   9, Trial:   0, SO: firefly_dynamic & metr        , currPerf: 6.30e-01, candPerf: 6.30e-01 which: entered
 :: Rep:   9, Step:   9, Trial:   1, SO: genetic_crossover & gree      , currPerf: 6.30e-01, candPerf: 6.30e-01 which: entered
 :: Rep:   9, Step:   9, Trial:   2, SO: local_random_walk & all       , currPerf: 6.30e-01, candPerf: 6.30e-01 which: entered    +
 :: Rep:   9, Step:  10, Trial:   0, SO: differential_mutation & prob  , currPerf: 6.30e-01, candPerf: 6.30e-01 which: entered
 :: Rep:   9, Step:  10, Trial:   1, SO: genetic_crossover & all       , currPerf: 6.30e-01, candPerf: 6.30e-01 which: entered
 :: Rep:   9, Step:  10, Trial:   2, SO: local_random_walk & metr      , currPerf: 6.30e-01, candPerf: 6.30e-01 which: entered
 :: Rep:   9, Step:  10, Trial:   3, SO: genetic_crossover & gree      , currPerf: 6.30e-01, candPerf: 6.30e-01 which: entered    +
 :: Rep:   9, Step:  11, Trial:   0, SO: genetic_crossover & prob      , currPerf: 6.30e-01, candPerf: 6.30e-01 which: entered
 :: Rep:   9, Step:  11, Trial:   1, SO: random_sample & gree          , currPerf: 6.30e-01, candPerf: 6.30e-01 which: entered
 :: Rep:   9, Step:  11, Trial:   2, SO: differential_mutation & prob  , currPerf: 6.30e-01, candPerf: 6.26e-01 which: entered    +
 :: Rep:   9, Step:  12, Trial:   0, SO: differential_mutation & prob  , currPerf: 6.26e-01, candPerf: 6.26e-01 which: entered
 :: Rep:   9, Step:  12, Trial:   1, SO: differential_mutation & metr  , currPerf: 6.26e-01, candPerf: 6.26e-01 which: entered
 :: Rep:   9, Step:  12, Trial:   2, SO: differential_mutation & prob  , currPerf: 6.26e-01, candPerf: 6.26e-01 which: entered    +
 :: Rep:   9, Step:  13, Trial:   0, SO: genetic_crossover & metr      , currPerf: 6.26e-01, candPerf: 6.26e-01 which: entered
 :: Rep:   9, Step:  13, Trial:   1, SO: random_search & all           , currPerf: 6.26e-01, candPerf: 6.26e-01 which: entered    +
 :: Rep:   9, Step:  14, Trial:   0, SO: genetic_crossover & metr      , currPerf: 6.26e-01, candPerf: 6.26e-01 which: entered
 :: Rep:   9, Step:  14, Trial:   1, SO: random_flight & all           , currPerf: 6.26e-01, candPerf: 6.26e-01 which: entered
 :: Rep:   9, Step:  14, Trial:   2, SO: genetic_crossover & metr      , currPerf: 6.26e-01, candPerf: 6.26e-01 which: entered
 :: Rep:   9, Step:  14, Trial:   3, SO: genetic_crossover & metr      , currPerf: 6.26e-01, candPerf: 6.26e-01 which: entered
 :: Rep:   9, Step:  14, Trial:   4, SO: random_search & all           , currPerf: 6.26e-01, candPerf: 6.26e-01 which: entered    +
 :: Rep:   9, Step:  15, Trial:   0, SO: differential_mutation & all   , currPerf: 6.26e-01, candPerf: 6.26e-01 which: entered    +
 :: Rep:   9, Step:  16, Trial:   0, SO: differential_mutation & gree  , currPerf: 6.26e-01, candPerf: 6.26e-01 which: entered    +
 :: Rep:   9, Step:  17, Trial:   0, SO: differential_mutation & gree  , currPerf: 6.26e-01, candPerf: 6.26e-01 which: entered
 :: Rep:   9, Step:  17, Trial:   1, SO: spiral_dynamic & prob         , currPerf: 6.26e-01, candPerf: 6.26e-01 which: entered
 :: Rep:   9, Step:  17, Trial:   2, SO: genetic_crossover & metr      , currPerf: 6.26e-01, candPerf: 6.26e-01 which: entered
 :: Rep:   9, Step:  17, Trial:   3, SO: central_force_dynamic & prob  , currPerf: 6.26e-01, candPerf: 6.26e-01 which: entered
 :: Rep:   9, Step:  17, Trial:   4, SO: differential_mutation & all   , currPerf: 6.26e-01, candPerf: 6.26e-01 which: entered    +
 :: Rep:   9, Step:  18, Trial:   0, SO: random_search & gree          , currPerf: 6.26e-01, candPerf: 6.26e-01 which: entered
 :: Rep:   9, Step:  18, Trial:   1, SO: differential_mutation & prob  , currPerf: 6.26e-01, candPerf: 6.26e-01 which: entered    +
 :: Rep:   9, Step:  19, Trial:   0, SO: random_flight & all           , currPerf: 6.26e-01, candPerf: 6.26e-01 which: entered
 :: Rep:   9, Step:  19, Trial:   1, SO: local_random_walk & gree      , currPerf: 6.26e-01, candPerf: 6.26e-01 which: entered
 :: Rep:   9, Step:  19, Trial:   2, SO: genetic_crossover & metr      , currPerf: 6.26e-01, candPerf: 6.26e-01 which: entered
 :: Rep:   9, Step:  19, Trial:   3, SO: differential_mutation & gree  , currPerf: 6.26e-01, candPerf: 6.26e-01 which: entered
 :: Rep:   9, Step:  19, Trial:   4, SO: random_search & gree          , currPerf: 6.26e-01, candPerf: 6.26e-01 which: entered    +
 :: Rep:   9, Step:  20, Trial:   0, SO: spiral_dynamic & prob         , currPerf: 6.26e-01, candPerf: 6.26e-01 which: entered    +
 :: Rep:   9, Step:  21, Trial:   0, SO: genetic_mutation & all        , currPerf: 6.26e-01, candPerf: 6.26e-01 which: entered
 :: Rep:   9, Step:  21, Trial:   1, SO: differential_mutation & gree  , currPerf: 6.26e-01, candPerf: 6.26e-01 which: entered    +
 :: Rep:   9, Step:  22, Trial:   0, SO: firefly_dynamic & gree        , currPerf: 6.26e-01, candPerf: 6.26e-01 which: entered
 :: Rep:   9, Step:  22, Trial:   1, SO: genetic_crossover & gree      , currPerf: 6.26e-01, candPerf: 6.26e-01 which: entered
 :: Rep:   9, Step:  22, Trial:   2, SO: random_search & gree          , currPerf: 6.26e-01, candPerf: 6.26e-01 which: entered    +
 :: Rep:   9, Step:  23, Trial:   0, SO: local_random_walk & metr      , currPerf: 6.26e-01, candPerf: 6.26e-01 which: entered
 :: Rep:   9, Step:  23, Trial:   1, SO: random_flight & all           , currPerf: 6.26e-01, candPerf: 6.26e-01 which: entered
 :: Rep:   9, Step:  23, Trial:   2, SO: genetic_crossover & metr      , currPerf: 6.26e-01, candPerf: 6.26e-01 which: entered
 :: Rep:   9, Step:  23, Trial:   3, SO: random_search & gree          , currPerf: 6.26e-01, candPerf: 6.26e-01 which: entered    +
 :: Rep:   9, Step:  24, Trial:   0, SO: random_flight & all           , currPerf: 6.26e-01, candPerf: 6.26e-01 which: entered    +
 :: Rep:   9, Step:  25, Trial:   0, SO: genetic_crossover & metr      , currPerf: 6.26e-01, candPerf: 6.26e-01 which: entered
 :: Rep:   9, Step:  25, Trial:   1, SO: genetic_crossover & gree      , currPerf: 6.26e-01, candPerf: 6.26e-01 which: entered
 :: Rep:   9, Step:  25, Trial:   2, SO: genetic_crossover & prob      , currPerf: 6.26e-01, candPerf: 6.26e-01 which: entered    +
 :: Rep:   9, Step:  26, Trial:   0, SO: swarm_dynamic & gree          , currPerf: 6.26e-01, candPerf: 6.26e-01 which: entered
 :: Rep:   9, Step:  26, Trial:   1, SO: random_search & gree          , currPerf: 6.26e-01, candPerf: 6.26e-01 which: entered
 :: Rep:   9, Step:  26, Trial:   2, SO: genetic_crossover & gree      , currPerf: 6.26e-01, candPerf: 6.26e-01 which: entered
 :: Rep:   9, Step:  26, Trial:   3, SO: swarm_dynamic & metr          , currPerf: 6.26e-01, candPerf: 6.26e-01 which: entered

### 📌 **Seção 3: Encontrando o valor ótimo da instância para comparação**
Nessa seção iremos encontrar o valor ótimo por meio de força bruta, para compararmos com o valor dado pela hyperheuristica

In [68]:
import numpy as np
from scipy.optimize import minimize
from customhys.benchmark_func import Sphere

def find_optimal_portfolio(portfolio_instance, risk_free_rate=0.03):
    """
    Encontra a solução ótima para o problema do portfólio, usando a mesma instância utilizada pela Hyper-Heurística.

    Parâmetros:
    - portfolio_instance (dict): Dicionário contendo "function", "boundaries", "returns" e "volatilities".
    - risk_free_rate (float): Taxa livre de risco para cálculo do Índice de Sharpe.

    Retorna:
    - dict contendo 'optimal_sharpe' e 'optimal_weights'.
    """

    def portfolio_evaluation(weights):
        """
        Função de avaliação do portfólio. Calcula o Índice de Sharpe negativo para minimização.
        """
        weights = np.array(weights)
        weights = weights / np.sum(weights) if np.sum(weights) != 0 else np.full_like(weights, 1 / len(weights))

        returns = np.array(portfolio_instance["returns"])
        expected_return = np.dot(weights, returns)

        risk_function = portfolio_instance["function"]
        risk = risk_function.get_func_val(weights)  # Calculando risco com Sphere

        sharpe_ratio = (expected_return - risk_free_rate) / risk if risk > 0 else -1e6
        return float(-sharpe_ratio)  # Negativo para minimizar

    # Restrição para garantir que a soma dos pesos seja 1
    def constraint_sum(weights):
        return np.sum(weights) - 1

    # Número de ativos na instância do problema
    n_assets = len(portfolio_instance["returns"])

    # Limites definidos na instância do problema
    bounds = list(zip(*portfolio_instance["boundaries"]))

    # Inicialização aleatória dos pesos normalizados
    initial_weights = np.random.rand(n_assets)
    initial_weights /= np.sum(initial_weights)

    # Otimizando usando SLSQP
    result = minimize(
        fun=portfolio_evaluation,
        x0=initial_weights,
        method='SLSQP',
        constraints={'type': 'eq', 'fun': constraint_sum},
        bounds=bounds
    )

    # Retornando o resultado como dicionário
    return {
        "optimal_sharpe": -result.fun,  # Pegamos o valor sem o sinal invertido
        "optimal_weights": result.x
    }

In [93]:
# 🔹 Exemplo de uso com o problema configurado
resultado = find_optimal_portfolio(portfolio_4_assets)
print(resultado)

{'optimal_sharpe': 0.30468681851762336, 'optimal_weights': array([0.27826767, 0.24590471, 0.3118653 , 0.16396232])}